name: Run Web Scraper

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:  # Allow manual triggering

jobs:
  run_scraper:
    runs-on: windows-latest  # Use Windows runner

    steps:
      # Checkout the repository to get access to the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js with the desired version
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use Node.js 16 or your desired version

      # Install selenium-webdriver and chromedriver
      - name: Install selenium-webdriver and chromedriver
        run: |
          npm install selenium-webdriver  # Install selenium-webdriver
          npm install chromedriver         # Install chromedriver

      # Run the scraper script
      - name: Run Scraper
        run: |
          node inx.js  # Execute your scraping script
