name: Run Web Scraper
on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes
  workflow_dispatch:  # Allow manual triggering

jobs:
  run_scraper:
    runs-on: windows-latest  # Use Windows runner

    steps:
      # Checkout the repository to get access to the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js with the desired version
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use Node.js 16 or your desired version

      # Install necessary dependencies
      - name: Install dependencies
        run: |
          npm install selenium-webdriver    # Install selenium-webdriver
          npm install chromedriver          # Install chromedriver
          npm install dotenv                # Install dotenv
          npm install firebase              # Install Firebase SDK

      # Set up Firebase environment variables (if necessary)
      - name: Set up environment variables
        run: |
          echo "FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" >> $GITHUB_ENV
          echo "FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }}" >> $GITHUB_ENV
          echo "FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" >> $GITHUB_ENV
          echo "FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}" >> $GITHUB_ENV
          echo "FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" >> $GITHUB_ENV
          echo "FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}" >> $GITHUB_ENV

      # Run the scraper script
      - name: Run Scraper
        run: |
          node inx.js  # Execute your scraping script
